### ISSUE TITLE
Brochure

### ISSUE THREAD

**Issue by big-heavy** [gsantella/evo-site#9]
**Evolution**
Alternative Physical Therapy & Wellness Studio

Address - 2510 7th Ave Altoona, PA 16602 814 944 6535

**OUR WELLNESS PROGRAM**

Have you completed your physical therapy and do not want to stop evolving?
    Our wellness program is a great way to continue your exercise program. We off several options including skilled wellness.
    Give us a call for more details.

**AT EVOLUTION**
 we treat patients with a variety of diagnoses and issues including, but not limited to, the following
 Back Pain / Stenosis / Herniated Discs
  Piriformis Syndrome / Sciatica 
    Arthritis 
    Neck Pain
   Post - Surgical Care
   Sports Injuiries 
   Postural Dysfunction
   Orthopedic Conditions
   Hip and Knee Pain 
   Shoulder Pain / Tendonitis 
   Ankle / Foot / Plantar Fasciitis
   Walking and Balance Difficulties
   Automotive Injuries
   Weakness 

**ABOUT Lindsay & Cameron**

 Lindsay Bainey, MPT 
 Co-Owner
     Linsday is a graduate of the University of Pittsburgh with 20 years of Physical Therapy experience. She has worked
     in both inpatient rehabilitation and outpatient settings, treating patients pediatric through geriatric with a multitude of 
    diagnoses 

Cameron Cheers, PTA
 Co-Owner
      Cameron is a graduate of Mount Aloysius College with 8 years' experience working inpatient rehab and skilled nursing as well as outpatient facilities. Cameron's special interests include sports recovery, work hardening programs, and Kinesiology taping.

**Comment by Ender-Malcolm** [comment]
Our Mission Statement
Our practice will be upheld by our core values and beliefs. We commit to provide the highest quality physical therapy while treating every individual with respect.

Evolution Alternative Physical Therapy and Wellness Studio:
is an alternative to traditional physical therapy outpatient clinics, offering a personalized experience in a low traffic environment. At Evolution, our patients are treated like our family. We believe in hands-on, one-on-one therapy and will tailor an individualized program to meet your specific needs.

Address:
2510 7th Ave
Altoona, PA 16602
814-944-6535

Evolution Alternative Physical Therapy & Wellness Studio
We are a Direct Access Facility. Physician's referrals are not necessary for most insurances.

It is an INDIIDUAL'S right to choose where they receive Physical Therapy Treatment. Ask for Evolution by name.

"I've had PT at more than 5 places - but never again. There is none better than Evolution. They are, to coin a phrase, "Simply the Best." There is an attitude that permeates the Entire space of Evolution; what can be done to make you feel better and get you back o normalcy? They are kind, caring, compassionate, and fun. Their blend of healing not only the body, but the mind and spirit as well and returning balance back to you (no pun intended) makes them deserving of a ten-star rating!" - Mark Perehinec
